### ISSUE TITLE
Tell an Open Data Story

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#86]
## Objective Goal: 
We have a set of standards and frameworks that let us accurately understand the impact of our D&I interventions on the health of open source communities.

**Note**: This intended to help people understand the work we're doing, and is not itself a single task. 

## Item list:
- [ ] Find an [open data](https://visual.ly/blog/data-sources/) set that includes any demographic data like gender, ethnicity, age, education.
- [ ] Use R or any other visualization tool, to generate insights.
- [ ] Post a link in comments / submit a pull request to folder https://github.com/mozilla/diversity/tree/master/outreachy/open-data-story

**Comment by guptatrisha97** [comment]
Hey, I would like to work on this for Outreachy. Can you please assign it to me? Thanks

**Comment by emmairwin** [comment]
@guptatrisha97   Hi again, I also noticed you were interested in the Open Demographic tasks, if you can let me know which one you want to work with, I will assign :)

**Comment by akshitac8** [comment]
Hello,
Is this bug open for solving. I would like to contribute on this.

Thank you.

**Comment by emmairwin** [comment]
Hi @akshitac8 this is an issue specifically for Outreachy applicants - if you are, please go ahead :)   
It's really just intended to give people an idea of the type of work we're doing - so don't worry about getting it right, so much as having fun. If you get stuck, or have questions please let me know.

**Comment by akshitac8** [comment]
@emmairwin yes, I am participating in outreachy for this round. It would be great to work on this issue and thank you for assigning the same.

**Comment by guptatrisha97** [comment]
@emmairwin since I've already submitted the Open Demographic tasks' pull requests for review, I would love to contribute to this issue as well, if it is still open. Thanks!

**Comment by akshitac8** [comment]
Hey, @emmairwin I have gone through the link given by you and by what I understand, I have to make something like this [story](https://insights.cincinnati-oh.gov/stories/s/Safer-Streets-Insights/mebb-mkhj).
Also, I found this [website](https://data.world/). I wanted to know whether I am proceeding in the right direction.

**Comment by emmairwin** [comment]
Hi @akshitac8 I would first of all say, don't worry about doing too much or making it look perfect like that website.  This is just a learning contribution.
Second I would  look to see if you can extract one insight from data.  For example, in the first link there was 'police calls for service' data.   Any insight you can visualize about those calls like, where the most calls came from (geographically), or demographic, or even the peak times of day... would be an insight.  And you can stop there.   Does this help?

**Comment by reCursedd** [comment]
Hello @emmairwin , I would love to work on this project. This looks very exciting.

**Comment by akshitac8** [comment]
@emmairwin That helps for sure! I would get back if I have any other doubts.

**Comment by akshitac8** [comment]
@emmairwin I have coded this `plot`. Is it correct? Am I supposed to do something more? Also, where should I upload the code for this plot.
![image](https://user-images.githubusercontent.com/21353757/37208605-ecbe4120-23c7-11e8-92e9-898f38079480.png)

**Comment by emmairwin** [comment]
@akshitac8 that looks great!    If you were to give a title, or description to this data, what would it be?  would it be about the number of calls in an area?    Why is East Price Hill so much different ?

**Comment by akshitac8** [comment]
@emmairwin I think a proper title would be **Area-wise Number of calls**. 
![area-wise number of calls](https://user-images.githubusercontent.com/21353757/37227360-0d754202-2403-11e8-9b1a-13d01df0bdc0.png)
Also, it seems that the reason for so high number of calls in **East Price Hill** is due to type `CELL` which is pretty high when compared to other types of reasons for calls. 
![resons for calls in east price hill 1](https://user-images.githubusercontent.com/21353757/37227510-86f50a0e-2403-11e8-9acc-4d13550a1546.png)
When the city that is 2nd in terms of calls i.e. Westwood is seen, it seems that the variation is much less there.
![reasons for calls in westwood 1](https://user-images.githubusercontent.com/21353757/37227502-83bf0b82-2403-11e8-8332-07bf755f5c33.png)

**Comment by emmairwin** [comment]
awesome!   Finally, what tools did you use for this (so other people can learn from you)

**Comment by emmairwin** [comment]
@reCursedd multiple people can work on these tasks, they are meant to show the type of work and tools we're using in this area of the project .    Please feel free to jump in, and let me know if you have any questions thanks!

**Comment by reCursedd** [comment]
Thanks a lot ... Started looking at the datasets. I'll try to come up with
something..

**Comment by akshitac8** [comment]
@emmairwin I used `pandas` and `matplotlib` in `python`. If this looks fine, can you guide me through how should I record my contributions!

**Comment by guptatrisha97** [comment]
@emmairwin, my open data story talks about the unequal gender pay. I took an open data set from government data (https://data.seattle.gov/api/views/tptv-57gf/rows.csv?accessType=DOWNLOAD) about Seattle, which is supposed to be one of the most up-tech cities in the US. I used the open data set to create this pie chart on JSfiddle which is pure testimony to the gender inequality in pay, even today and even in a city like Seattle. This is the pie chart. Does it look fine?
![gender unequal pay](https://user-images.githubusercontent.com/35959848/37252282-8cfcd36c-2559-11e8-9ba1-c9813d53abe9.png)

**Comment by emmairwin** [comment]
@guptatrisha97  this is great!  Thank you!  this type of data story can help us understand how our attempts to improve things work or not. It's what we're trying to get better at in our d&I work.  By understanding where we are, we can improve.  Thank you!

**Comment by akshitac8** [comment]
@emmairwin  Do, I need to make any further changes in the issue and can you tell where should I generate a PR so that I can record my contribution for the outreachy program.

Thank you:)

**Comment by guptatrisha97** [comment]
@emmairwin please let me know how to record my contribution as a pull request. Thanks!

**Comment by edyasikpo** [comment]
@emmairwin i would love to work on this for the Outreach program but i really dont know how to go about it?

**Comment by reCursedd** [comment]
@emmairwin , this is what I made, can you please tell me how it looks or suggest some improvements? Is it ok to make it in google doc?
https://docs.google.com/document/d/1GzElk76g2ouvxoCOe5asieMSBhidxlkt_UpGiStZ9TI/edit?usp=sharing
Also, please let me know how to record my contributions as well. Should I fork this project?
Thanks

**Comment by reCursedd** [comment]
@edyasikpo , the very first step I followed, was to find an open data set of your choice.

**Comment by emmairwin** [comment]
@akshitac8 do you need to have a pull request?  or can I just validate this as a contribution via this comment? If you would like to do a pull request then please submit to the code base in a new folder called 'Open Data Story'.  Thank you so much

**Comment by emmairwin** [comment]
@edyasikpo we do a lot of analysis of data where diversity demographics like gender, race, age, location, education are present.

Often this means looking at existing data and seeing what we can understand.   This task asks you to to find any open data set, and to create a visual from that data that tells a story about.  It doesn't have to be on any topic, I just want to see that you can a) work with data,  b) create visuals, and c) can share what that data tells you about a certain demographic.   Does this help

**Comment by emmairwin** [comment]
@reCursedd awesome!  If you can please submit a Pull Request to https://github.com/mozilla/diversity/tree/master/outreachy/open-data-story

**Comment by akshitac8** [comment]
@emmairwin I have generated the PR for the respective issue.
Please review the PR :) and also I think we add a travis file also .

Thank you:)

**Comment by BANSAL-PALLAVI** [comment]
Hi @emmairwin I am willing to participate in outreachy. I have used adult income data set from the UCI ML repository.
Description of the data set: Shows gender, income, education, race, occupation etc.
I have generated a plot for finding the number of people who have income above or below 50k on the basis of gender.
![rplot02](https://user-images.githubusercontent.com/17240554/37318226-626fc118-268f-11e8-9a24-14a967f9736b.png)

**Comment by BANSAL-PALLAVI** [comment]
This plot helps us in understanding that very less number of women earn more than 50k compared to men. From this data we might question about the education received by both men and women. In the below box plot, we see that more number of men receive higher education. And thus more number if men earn > 50k as compared to women.
![rplot03](https://user-images.githubusercontent.com/17240554/37320044-e293715c-2697-11e8-9156-4ef29e09fcdf.png)

**Comment by BANSAL-PALLAVI** [comment]
I am using R to generate insights.

**Comment by guptatrisha97** [comment]
@emmairwin I am a bit confused. Should I submit a pull request or add my story to the folder you created?

**Comment by marimeireles** [comment]
@emmairwin 
I'd like to contribute to this project too, if it's okay.

**Comment by Rupal-IIITD** [comment]
@emmairwin 
I had some personal doubts regarding the projects/issues/tasks, so I have emailed you. I hope it's cool with you. :)

**Comment by reCursedd** [comment]
@emmairwin Thankyou so much, I will try to do that. Also, I would want to thank @akshitac8 , I think I found a marvelous counterpart of docs in Jupiter notebook to describe the data story along with the code. :)

**Comment by emmairwin** [comment]
@BANSAL-PALLAVI   Thanks!   
@Rupal-IIITD I will get to my email later today 
 @reCursedd  thank you!   and great to call out help from @akshitac8 
@marimeireles of course! please do.
@guptatrisha97 the pull request would be adding to the folder (same thing).

**Comment by akshitac8** [comment]
Thank you :) @emmairwin

**Comment by BANSAL-PALLAVI** [comment]
@emmairwin can I generate a pull request for the data story that I posted above?

**Comment by akshitac8** [comment]
Thank you @reCursedd

**Comment by emmairwin** [comment]
@BANSAL-PALLAVI yes please do thank you!

**Comment by emmairwin** [comment]
Closing this one, to create a new version.

**Comment by emmairwin** [comment]
reopening for someone who still wants to reference.

**Comment by poojasr89** [comment]
https://github.com/poojasr89/Inventors

**Comment by poojasr89** [comment]
East v/s West  
Comparision of statistics of women inventors in California v/s Masssachusetts.

Following infographic may serve to any Masters or PhD graduate who is deciding on where to start her research career.
The assumption is that patented inventions indicate an orientation towards research, although the underlying motivation is corporate profits.
![inventors_16](https://user-images.githubusercontent.com/37288394/37561560-9a5dc2d2-2a0e-11e8-970e-4f507d69e254.PNG)
Refer to the above graph. Although population of CA is higher, percentage of patent grantees in MA is higher than that in CA.
Let us look at how population of just CA and MA have evolved over time v/s percentage patent grantees from these two states:
![inventors_v20](https://user-images.githubusercontent.com/37288394/37561573-bc8f4984-2a0e-11e8-9fdb-e37c79d44cce.PNG)

Another interesting data to look at is the categories in which these patents were awarded in CA and MA: 
![inventors_v11_categories](https://user-images.githubusercontent.com/37288394/37561580-fcdd57ba-2a0e-11e8-89dd-c00a946f8a5a.PNG)

As we had noticed earlier, the total number of patent grantees (as % of population) is higher in MA. Inventions percentage in computers and electronic industries are very identical in the two states where as there is drastic difference in chemical and medical (drugs based) inventions.

Since we are interested in women inventors, let us only focus on female population in CA and MA over time v/s female patent grantees from these two states: 

![inventors_v21_womenonly](https://user-images.githubusercontent.com/37288394/37561587-27b218cc-2a0f-11e8-97d4-8e20695a22f2.PNG)

  - It is interesting to see the comparison of Male and Female population in CA and MA v/s Male and Female patent grantees
 Now, let us look at how many women under 30 years of age have become patent grantees in CA and MA :
![inventors_v24](https://user-images.githubusercontent.com/37288394/37561645-fe976314-2a10-11e8-81ba-aea172b014f5.png)


Inference: Although there is an overall decline in the number of young women inventors, the data shows that Massachusetts is more conducive to women inventors in the fields of chemical and medical research than other states. 

Tools used: Python with Pandas and Matplotlib

**Comment by Rupal-IIITD** [comment]
@emmairwin 

I am applying to Outreachy this year. I want to contribute to this issue, can I also submit my report?

I found an interesting idea online which involves network analysis done on a network formed using genes of coronary artery disease. (Database: CADGene Disease database). I have some interesting ideas in mind regarding this: asking relevant questions to this network and taking out useful insights and inferences from it.
Technologies that I am using are: 
**Cytoscape** (FOSS platform for visualising complex gene networks graphically and producing visually and aesthetically appealing results)
**NetworkX** (a Python language software package for the study of complex networks.)

This is a part of a Network Science project I am personally working on since past few days. The part of which I wish to share here, for now, is just a beginning of it, I will keep on updating my report as and when I progress with it.

This is mainly to demonstrate you that I can comfortably analyze and manipulate the data to understand it, produce useful results from it and mold it to answer some very non-trivial queries which can't be observed from a bare human eye, which needs to be computed by systems.

Although I understand that the deadline for Outreachy is just round the corner. so I am submitting the work I have been able to progress with till date and submit my Outreachy application. I will keep on contributing to this project after the deadline too.

Is it alright with you, Emma?
If there's anything that concerns you, feel free to let me know. :)

**Comment by emmairwin** [comment]
@poojasr89 this is excellent!  what data source did you use?

**Comment by emmairwin** [comment]
> This is mainly to demonstrate you that I can comfortably analyze and manipulate the data to understand it, produce useful results from it and mold it to answer some very non-trivial queries which can't be observed from a bare human eye, which needs to be computed by systems.

@Rupal-IIITD this sounds very interesting, and great!  than you!

**Comment by poojasr89** [comment]
@emmairwin Thank you, Emma.
The data source used 
http://www.equality-of-opportunity.org/data/patents/table_2b.csv

**Comment by Rupal-IIITD** [comment]
Hi, Emma.

1. I am in the process of making my proposal for Outreachy for "Diversity and Inclusion" project of Mozilla. Can you share a template of the application proposal that you prefer as an evaluator while evaluating our profiles?
I found [this ](https://wiki.mozilla.org/SummerOfCode/ApplicationTemplate)template at Mozilla's GSoC ideas page. But since I am applying to Outreachy (and not GSoC), kindly let me know the proposal template w.r.t to this particular project.

2. For making contributions, do I compulsorily need to create PR's to Mozilla's GitHub page or can I upload materials to my account's repo one by one (as I will keep on contributing to it after the deadline too), and mention the link to that Repository in the application form? What do you prefer?

**Comment by KarinRoe** [comment]
I had a look at the Salary from state employee from the year 2007 to 2017 in IOWA
The plot shows the total salary instead of mean which I am working on right now.

![rplot](https://user-images.githubusercontent.com/37213457/37687385-55bf90ce-2c93-11e8-9940-1e44c5e6a0ee.png)

**Comment by Rupal-IIITD** [comment]
@emmairwin 

Outreachy's page says:

> Your final application will ask you to fill out a timeline for the internship project. If you have trouble with this, or a mentor tells you they don't want you to fill out the timeline, you should simply note any full-time commitments you'll have during the internship period that will impact your work.

> Try to break down each big internship task into several smaller tasks, until you have an idea of what you'll be working for each week of the 12 week internship. All projects will have some tasks where the details will be vague until the time you start the task. It is fine to provide higher-level descriptions of what you'll be working on.

Can you give some light on this? How do we formulate our timeline/application as a whole?

**Comment by ccaddel** [comment]
I looked at the Race and Economic Opportunity in the United States: An Intergenerational Perspective dataset from The Equality of Opportunity Project: http://www.equality-of-opportunity.org/data/

Here are my insights, which I used RStudio to generate: [file:///Users/christinacaddel/Desktop/DATA/Outreachy/EEO_race.html](url)

I do have other projects in which I've used other programming languages to generate insight: https://github.com/ccaddel

Please let me know if anything else is needed to record my contribution.

Thanks!

**Comment by marimeireles** [comment]
Hey, @emmairwin 
I've just finished my contribution and I've updated my results to my [personal repo](https://github.com/marimeireles/twitter-scrapper), you can check my results on the readme file.
I have to say I've spent hours looking for a data set that would inspire me to do something cool but I didn't find anything that's why I created a small one using Twitter API. I hope it's not a problem, since now it's an open data set too.
Let me know if there is anything you think I should change or improve.
Thanks!

**Comment by marimeireles** [comment]
Hi @ccaddel 
I'm just a contributor to the project but I think I can help.
I've sent an email to Emma today and I got the response that she is going to be away till march 28th and she said we could email Lizz to talk about Outreachy, this is her email: lizz@mozilla.com
If you need it here is Emma email: eirwin@mozilla.com 
About the application I believe the deadline depends on your timezone, but you should probably talk to Lizz or Emma.
Good luck!

**Comment by emmairwin** [comment]
Thanks @ccaddel  :)

**Comment by emmairwin** [comment]
@marimeireles  thanks for helping :)

**Comment by marimeireles** [comment]
Hi @emmairwin, sorry to bother, but, can I record this [contribution ](https://github.com/mozilla/diversity/issues/86#issuecomment-375273615) on my Outreachy page? I'm not sure if you saw my comment.
