### ISSUE TITLE
Gender Identity  - Clarity for use of fields

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#95]
From @jofish
https://github.com/mozilla/diversity/blob/master/data-metrics/surveys/en/gender-identity.md

it’s labelled Gender Identity, and then there’s two questions, one labelled Gender Identity and one labeled Transgender. Is the implication that if one asks one, one should ask the other? I don’t think so; that best practices doc (https://github.com/mozilla/diversity/blob/master/data-metrics/surveys/best-practices-diverse-data.md) makes it very clear that one shouldn’t ask without a good reason, but putting the two after each other might suggest that.

**Comment by akshitac8** [comment]
Hey @emmairwin  I have written a :book: [blog-post](https://channelcs.github.io/gender-identity.html#designing-forms-for-gender-identity
) for this question. It would be great if you could have a look at it. Also, I request you to suggest any changes required. Thanks. :smile:

**Comment by akshitac8** [comment]
If this looks good, may I also generate a PR as a `MD` file?

**Comment by reCursedd** [comment]
Hello @emmairwin , please let me know what you think!

I think the questions labeled 'Gender Identity'  and 'Transgender' should be two individual questions as they can be used by an organization to deduce separate analysis results. According to the best practices doc if we don't require an information, we don't ask for it. 
But I believe, while collecting demographic data and performing analysis over it, the purpose is mostly to understand the implications of a gender on various things, rather than the Biological term associated with it. I think both the questions are inclusive of each other if we want to understand the gender-identity in a wholesome manner. But nonetheless, if a single answer suffices we shouldn't ask for the second information.

**Comment by emmairwin** [comment]
@akshitac8 sorry I was on a small break!   Yes please do propose as an MD file.   I  need to organize some of this into best practices, and will do that once you submit.  thanks!

**Comment by emmairwin** [comment]
@reCursedd thanks for your thoughts, and I agree.  I think by asking ourselves *why* we ask specific questions in advance, then we get better at ensuring we look for those insights afterwards.  That said, you are right to say they are inclusive of each other - I know in our survey last year people were happy to see as two separate questions, when often they are merged together.

**Comment by reCursedd** [comment]
@emmairwin , thanks for the task :)

**Comment by AshmyAchu** [comment]
Hello @emmairwin,
Based on my understandings from the comments, I agree with what @reCursedd has said, that if a single answer suffices we shouldn't ask for the second information. The simplest questions can make a big difference in shaping people's experience with any product or organisation, and the concept of inclusion demands that every person gets the same fair experience. Since gender identity is an important source of data, it is often important that we make it a mandatory question in forms. 
However, I think the issue that needs to be considered here is regarding the gender identity shift that transgenders have experienced. For them, their state of mind on one particular day may have an effect on their gender identity. Hence, I think that though both questions are inclusive of each other, we should ask the second question too. Maybe we should give people a chance to express their 'confusion', though the word is not that right, over gender identity too. We can preferably put in sexual orientation and gender identity fields separately. 
Thank you :)

**Comment by Rupal-IIITD** [comment]
I have written a small report on this issue here:

https://github.com/Rupal-IIITD/Outreachy-contributions/blob/master/Gender%20Identity%20-%20Clarity%20for%20use%20of%20Fields.md

(I have also submitted this link as a PR for OUtreachy purposes)

I'd love to get your feedback on it.

@emmairwin @jofish

**Comment by akshitac8** [comment]
Hey @emmairwin I have generated the PR #98 regarding this issue. I somewhat agree with @reCursedd. One thing I would like to add is that, when designing Gender Identity Forms, we should consider is the sensitivity of the matter and people’s perception which should come first rather than just collecting demographic data for data manipulation.

**Comment by reCursedd** [comment]
@akshitac8 yes, I totally agree to that. I realized that it's a very essential part when I went through your wonderful blog post. I think the primary approach towards diversity and inclusion is to be empathetic and mindful.
