### ISSUE TITLE
Gender Identity - Legal Concerns (age)

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#96]
from @jofish

 I wanted to ask one detail about that best practices doc: you claim you can’t ask gender identity for people under 19. I think that might need some substantiation. 

Why 19? COPPA applies in the US for <13s, and that’s definitely the general rule I’ve seen working in industry in the US. And <19 would mean, say, you couldn’t ask a college freshman who wanted to live in a single-sex dorm their sex. If we’re going to state things like that strongly, presumably we should have a pretty good logic for doing so and be transparent about that logic.

**Comment by akshitac8** [comment]
Hey @emmairwin  I have written a :book: [blog-post](https://channelcs.github.io/gender-identity.html) for this question. It would be great if you could have a look at it. Also, I request you to suggest any changes required. Thanks. :smile:

**Comment by marimeireles** [comment]
I've done some research and I've learned a number of factors that might prevent people under 19 to express their gender in a survey.  

School victimization of Lesbian, gay, bisexual, and transgender‐related is strongly linked to young adult mental and physical health [[1]](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1746-1561.2011.00583.x). I believe that part of the LGBT+ teenagers that are in high school might not want to reveal their genders because they don't want to take the risk of suffering school victimization and suffering because of that. Even though the data might have standards that will ensure that final results will be anonymotized beyond any recognition adolescents often lack privacy when completing surveys [[2]](https://williamsinstitute.law.ucla.edu/wp-content/uploads/geniuss-report-sep-2014.pdf) and that lack of privacy may be a relevant cause for them to fear school victimization and other kinds of negative consequences.

Another reason why we shouldn't accept gender related answers from people with less than 19 years old might be that a considerable part of teenagers who answer the survey may not be fully familiarized with terms like "transgender", like the study [[2]](https://williamsinstitute.law.ucla.edu/wp-content/uploads/geniuss-report-sep-2014.pdf) points out. I imagine that other terms like "non-binary", "gender fluid" and "genderqueer" might also be equally confusing preventing some people to express themselves correctly.

**Comment by emmairwin** [comment]
@akshitac8 and @marimeireles thanks for these wonderful responses and research!   I think there are so many things to consider, and that standards for asking questions might look more like a decision tree and where age is only appropriate given specific legal, regional, ethical perspectives.  

To your last point @marimeireles we did find that providing too many choices - wasn't really better than providing an other___ field, because there are always other ways people want to identify AND yes it confuses some people. I wrote a bit of a post on that here:  https://medium.com/@sunnydeveloper/what-we-learned-about-gender-identity-in-open-source-d9acea0b7586

**Comment by Rupal-IIITD** [comment]
I have created a report on my stand on this question:

https://github.com/Rupal-IIITD/Outreachy-contributions/blob/master/Gender%20Identity%20-%20Legal%20Concerns%20(age).md

I support the idea that we can and _should_ talk about gender-related issues and questions with teenagers, and I have mentioned my reasons in this report.

(I have also created a PR for it for Outreachy purposes.)

I'd love to know what you guys think. Feedback is most welcomed.

@emmairwin @marimeireles

**Comment by Rupal-IIITD** [comment]
I'll directly quote my thoughts here:

I want to throw some light towards another side of the coin. **I support the idea that we shouldn't limit the survey questions on Legal Concerns based on some age bar such as 19**, as mentioned in #96

- By asking the gender-specific questions from a teenager i.e person <=19 years of age can be of a lot of help for **producing statistics which can address the issues of those who feel that they need community support due their gender issues or if they are facing self-acceptance issues because their gender doesn't match with their in-born sex**. If we could collect truthful data, it will help us understand the need to take required steps for those who are looking for support and inclusiveness but are too afraid to ask or talk about it openly and freely. We can get their responses through anonymized forms.

And I'd say, this becomes even more crucial in case of teenagers by extending them help at a younger age so that they are not scarred for life due to victimization and due to their apprehension to talk about it or to raise a voice against it. We could possibly introduce them to the online communities that are available for people between the age of 13 and 19 which they can join to connect with other Gender-expansive youth and their allies.

But for this, **we _need_ to gather their honest answers. Just closing the matter at "them being not comfortable" won't solve this persistent problem.**

- Through such surveys, we can get an idea of how many people ticked that "I don't understand such jargons" or "I haven't heard of such a dissection of genders ever before" to get a sense of **where our "Gender Education" lies in the real world**. Are we actually able to educate people regarding this or are these just bookish terms? 

This will help us know that who all need to be made more educated and self-aware, and how to make them understand what is meant by "self-acceptance".

And I'd emphasize on the fact that it's better to help the people understand and aware of such things during teenage rather than during their 30's when they already would have gone through worst horrors of the societal mentality (which I hope is changing slowly).

And I don't really think that people under 19 years of age are not grown/mature/aware/mentally prepared enough to talk about gender? Or sex? If I talk in the context of the society where I live, even the Child Labour law is applicable only to children below 14 years of age. Which means, the government considers children >14 to be grown-ups.

And even if there are not yet aware of "Gender Issues" before 19, our responsibility should be to educate them on this subject and not to put the matter aside for somebody else to solve.

It is as important as **Sex Education**. (Lack of which is creating fatal consequences in India; like the ever-increasing rate of rapes and sexual, physical and mental harassment cases.)

These children are the future of the nation. Educating them would help in creating a better society for the future which will be more inclusive, accepting and open-minded.

- One more thing that I observed in some gender-related surveys is: **"Are you a straight male or a straight female?"**

**I don't approve of this. I feel that we have got the fundamental terminologies very wrong. Calling only heterosexual people as "straight" is itself a sexist statement. And asking out some non-heterosexual being a question whether they are a straight gender or not is outright derogation. It can be offensive to someone who is sensitive to such topics, including myself.**

**Comment by marimeireles** [comment]
Hi @Rupal-IIITD 
I think you've made a very relevant point saying that we should empower people with less than 19 years old to learn more about gender identity and encourage them to express themselves. I agree with you and I think it'd be great to do something like this.
But from what I understood from the issues that were proposed here the purpouse of the questionnaire isn't to teach people about gender or to help them in that matter. Even though I think everything you said is relevant I believe it's not in the scope of the questionnaire.
My answer is focused on answering @jofish's question specifically. And I believe that preventing people under 19 responding the gender questionnaire will probably generate cleaner data because of the points I emphasized in my answer.

**Comment by Rupal-IIITD** [comment]
Hi, 
I understand what you meant to convey.
What I tried to suggest is that rather than restricting gender specific questions to people >19, what we should do is that we should keep another option of "I don't understand such jargons", "Not comfortable to say", "Haven't heard of such a dissection of genders ever before" etc. to know a more real scenario. And this would help us create a cleaner data. And then we can let organisations take required steps. But collection of a more realistic data is the pre-requisite for that.

What do you think?

**Comment by Rupal-IIITD** [comment]
@emmairwin
Would love to know your take on this.

**Comment by akshitac8** [comment]
Hi @Rupal-IIITD 
I'm also a fellow contributor to the project but I think I can help.
Emma is might be little busy with the new quarter starting and the open source community call. She will respond don't worry. Good luck :slightly_smiling_face:

**Comment by Rupal-IIITD** [comment]
Then we wouldn't be able to figure out the fundamental reason for people choosing "Prefer not to say". How will we decode it, because we need to (for the reasons I stated above)?

**Comment by reCursedd** [comment]
I think whether we need to decode it depends on whether we need that particular piece of information. You can as well just work with the given/provided data of gender identity to satiate your questions/curiosity. 
I agree with you @Rupal-IIITD that we won't be able to figure out the fundamental reason that way. But first we need to ask ourselves do we need that information? (I understand why it is essential) but I feel it shouldn't be a mandatory question for collecting data for Gender Identity (a person might have a personal reason to not answer). 
What I feel is we should go by a baseline law like COPPA as mentioned by @emmairwin , just to keep things generic and simple. Answers to this question has equally valid arguments on both sides of debate, as already discussed above. But if we keep our baseline in parallel with a widely accepted baseline then it will be easy to analyze over cross platform data (eg. data from more than one source or area) or merger data with different timeline.
